#!/bin/sh

###
# Script will install a small HTML5 project
# Running: ~/ . project [project-name] [type] [sh]
# by appending the . this project will jump into the directory path created at /project/dev
###

###
## types
#
# exp           - Basic fast deploy experiment mode, designed for css and minimal js tests
# es6           - The Future - browserify for node in the frontend / common js modules
# node-server   - Creates a skeleton express app

# assign default type if none given
TYPE=${2:-exp}

# set scripts path
SCRIPTS=~/Sync/Code/Generators/build-scripts

# import relevant script
case "$TYPE" in

  node-server)
    LOCATION=~/Sites/_NODE
    cd $LOCATION
    . $SCRIPTS/.node-server
    ;;
  es6)
    LOCATION=~/Sites/_MODULES
    cd $LOCATION
    . $SCRIPTS/.es6
    ;;
  *)  
    LOCATION=~/Sites/_VANILA
    cd $LOCATION
    . $SCRIPTS/.exp
    ;;
esac

# exit into new project
cd $LOCATION/$1