#!/bin/sh -x

###
# Script will install a small HTML5 project
# Running: ~/ . project [project-name] [type]
# by appending the . this project will jump into the directory path created at /project/dev
###

###
## types
#
# exp           - Basic fast deploy experiment mode, designed for css and minimal js tests
# browserify    - The Future - browserify for node in the frontend / common js modules
# express       - Creates a skeleton express app

# assign default type if none given
TYPE=${2:-exp}

# set scripts path
SCRIPTS=~/Sync/Code/Generators/build-scripts

# import relevant script
case "$TYPE" in

  express)
    LOCATION=. 
    cd $LOCATION
    . $SCRIPTS/.node-express
    ;;
  browserify)
    LOCATION=.
    . $SCRIPTS/.browserify
    ;;
  requirejs)
    LOCATION=. 
    . $SCRIPTS/.amd
    ;;
  *)  
    LOCATION=.
    cd $LOCATION
    . $SCRIPTS/.exp
    ;;
esac

s . # open with sublime